# Generated by Django 4.1.2 on 2022-11-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('showName', models.CharField(max_length=128)),
                ('showNameShort', models.CharField(default='', max_length=8)),
                ('venue', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False)),
                ('projectCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
