# Generated by Django 4.1.2 on 2022-11-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WorkNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('forGroup', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=5)),
                ('noteText', models.CharField(max_length=256)),
                ('channelList', models.CharField(max_length=32)),
                ('changeFieldSelection', models.CharField(choices=[('Instrument Type', 'INSTRUMENT_TYPE'), ('Position', 'POSITION'), ('Unit Number', 'UNIT_NUMBER'), ('Accessory', 'ACCESSORY'), ('Color', 'COLOR'), ('Gobo', 'GOBO'), ('Gobo Size', 'GOBO_SIZE'), ('Purpose', 'PURPOSE'), ('Dimmer', 'DIMMER'), ('Circuit', 'CIRCUIT'), ('Breakout', 'BREAKOUT'), ('Dimmer Phase', 'DIMMER_PHASE'), ('Address', 'ADDRESS'), ('Universe', 'UNIVERSE'), ('Channel', 'CHANNEL')], default='INSTRUMENT_TYPE', max_length=16)),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedBy', to='notes.assignee')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to='accounts.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
