# Generated by Django 4.1.2 on 2022-10-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=5)),
                ('noteText', models.CharField(max_length=256)),
                ('channelList', models.CharField(max_length=5)),
                ('changeFieldSelection', models.CharField(choices=[('Instrument Type', 'INSTRUMENT_TYPE'), ('Position', 'POSITION'), ('Unit Number', 'UNIT_NUMBER'), ('Accessory', 'ACCESSORY'), ('Color', 'COLOR'), ('Gobo', 'GOBO'), ('Gobo Size', 'GOBO_SIZE'), ('Purpose', 'PURPOSE'), ('Dimmer', 'DIMMER'), ('Circuit', 'CIRCUIT'), ('Breakout', 'BREAKOUT'), ('Dimmer Phase', 'DIMMER_PHASE'), ('Address', 'ADDRESS'), ('Universe', 'UNIVERSE'), ('Channel', 'CHANNEL')], default='INSTRUMENT_TYPE', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
