# Generated by Django 4.1.2 on 2022-11-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknote',
            name='cue',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='worknote',
            name='channelList',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='worknote',
            name='noteText',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
