# Generated by Django 4.1.2 on 2022-10-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_worknote_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknote',
            name='assignedTo',
            field=models.CharField(choices=[('Production Electrician', 'PRODUCTION_ELECTRICIAN'), ('Designer', 'DESIGNER'), ('Programmer', 'PROGRAMMER')], default='PRODUCTION_ELECTRICIAN', max_length=32),
        ),
    ]
