# Generated by Django 4.1.2 on 2022-10-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_worknote_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknote',
            name='forGroup',
            field=models.BooleanField(default=False),
        ),
    ]
