# Generated by Django 4.1.2 on 2022-11-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gobo',
            name='goboCode',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='gobo',
            name='goboName',
            field=models.CharField(max_length=64),
        ),
    ]
