# Generated by Django 4.1.2 on 2022-11-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cueList', '0002_alter_cuelist_cuelistnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cue',
            name='cueTime',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='cue',
            name='eosCueNumber',
            field=models.FloatField(default=1),
        ),
    ]
