# Generated by Django 4.1.2 on 2022-11-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cueList', '0003_alter_cue_cuetime_alter_cue_eoscuenumber'),
        ('script', '0002_alter_script_scriptname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CueAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.IntegerField(default=1)),
                ('xPos', models.FloatField(default=0)),
                ('yPos', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('cue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cueList.cue')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script.script')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
